# Generated by Django 5.0.4 on 2024-04-29 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gente',
            name='lastChosen',
            field=models.DateField(default=datetime.date(2001, 1, 1)),
        ),
    ]
