# Generated by Django 5.0.4 on 2024-05-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='msg',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
